apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: careline360
resources:
  - namespace.yaml
  - configmap/app-config.yaml
  - secrets/app-secrets.example.yaml
  - services/mongodb.yaml
  - services/rabbitmq.yaml
  - services/auth-service.yaml
  - services/admin-service.yaml
  - services/emergency-service.yaml
  - services/patient-service.yaml
  - services/doctor-service.yaml
  - services/appointment-service.yaml
  - ingress/careline360-ingress.yaml
